
const Universities = [
  "Abia State University", 
  "Abubakar Tafawa Balewa University", 
  "Achievers University, Owo", 
  "Adamawa State University", 
  "Adekunle Ajasin University", 
  "Adeleke University", 
  "Afe Babalola University", 
  "Ahmadu Bello University", 
  "Ajayi Crowther University", 
  "Akwa Ibom State University", 
  "Al-Hikmah University", 
  "Al-Qalam University, Katsina", 
  "Ambrose Alli University", 
  "American University of Nigeria", 
  "Babcock University", 
  "Bauchi State University", 
  "Bayero University Kano", 
  "Baze University", 
  "Bells University of Technology", 
  "Benson Idahosa University", 
  "Benue State University", 
  "Bingham University", 
  "Borno State University", 
  "Bowen University", 
  "Caleb University", 
  "Caritas University", 
  "Chrisland University", 
  "Chukwuemeka Odumegwu Ojukwu University", 
  "Clifford University", 
  "Coal City University", 
  "Covenant University", 
  "Crawford University", 
  "Crescent University, Abeokuta", 
  "Cross River University of Technology", 
  "Crown Hill University", 
  "Delta State University, Abraka", 
  "Dominican University, Ibadan", 
  "Eastern Palm University", 
  "Ebonyi State University", 
  "Edo State University", 
  "Edwin Clark University", 
  "Ekiti State University, Ado Ekiti", 
  "Eko University of Medical and Health Sciences", 
  "Elizade University", 
  "Enugu State University of Science and Technology", 
  "Evangel University Akaeze", 
  "Federal University of Agriculture, Abeokuta", 
  "Federal University of Petroleum Resources", 
  "Federal University of Technology, Akure", 
  "Federal University of Technology, Minna", 
  "Federal University of Technology, Owerri", 
  "Federal University, Birnin Kebbi", 
  "Federal University, Dutse", 
  "Federal University, Dutsin-Ma", 
  "Federal University, Gashua", 
  "Federal University, Gusau", 
  "Federal University, Kashere", 
  "Federal University, Lafia", 
  "Federal University, Lokoja", 
  "Federal University, Ndufu-Alike", 
  "Federal University, Otuoke", 
  "Federal University, Oye-Ekiti", 
  "Federal University, Wukari", 
  "Fountain University", 
  "Gombe State University", 
  "Gombe State University of Science and Technology", 
  "Ibrahim Badamasi Babangida University", 
  "Igbinedion University Okada", 
  "Imo State University", 
  "Kaduna State University", 
  "Kano University of Science and Technology", 
  "Kebbi State University of Science and Technology", 
  "Kings University", 
  "Kogi State University", 
  "Kwara State University", 
  "Ladoke Akintola University of Technology", 
  "Lagos State University", 
  "Landmark University", 
  "Lead City University", 
  "Madonna University, Okija", 
  "Nasarawa State University", 
  "Niger Delta University", 
  "Nile University of Nigeria", 
  "Nnamdi Azikiwe University",
  "Northwest University Kano",
  "Obafemi Awolowo University",
  "Ondo State University of Science and Technology",
  "Osun State University",
  "Pan African University",
  "Plateau State University",
  "Redeemer's University",
  "Rivers State University of Science and Technology",
  "Sokoto State University",
  "Taraba State University",
  "Umaru Musa Yar'Adua University",
  "University of Abuja",
  "University of Africa, Toru-Orua",
  "University of Agriculture, Makurdi",
  "University of Benin",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Medical Sciences, Ondo",
  "University of Nigeria",
  "University of Port Harcourt",
  "University of Uyo",
  "Usman Danfodio University",
  "Veritas University",
  "Western Delta University",
  "Yobe State University"
];